### ISSUE TITLE
where is training_mapping.txt?

### ISSUE THREAD

**Issue by yxy1995123** [arangesh/Ground-Plane-Polling#1]
when I run prepare_kitti_data.py,there is a problem:File "/media/dl/4T/yang/3D/Ground-Plane-Polling/prepare_kitti_data.py", line 35, in get_image_to_video_mapping
    with open(os.path.join(devkit_dir, 'mapping', 'train_mapping.txt'), 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: '/media/dl/4T/Dataset/KITTI_GPP/raw/devkit_object/mapping/train_mapping.txt'.
So how to produce /train_mapping.txt?
Thank you very much!

**Comment by arangesh** [comment]
This is a text file available in KITTIs 3D object detection development kit. You can download it from [this page](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d).
