### ISSUE TITLE
models trained on KITTI

### ISSUE THREAD

**Issue by zsnihao** [arangesh/Ground-Plane-Polling#2]
hello：
      I don not download models trained ，can you give me a new link? thinks.

**Comment by arangesh** [comment]
You can download our inference models trained on KITTI using [this link](https://drive.google.com/file/d/10ZIrDwySKl0jcFDYnEVo_s--yh88WVB8/view?usp=sharing).

**Comment by zsnihao** [comment]
thanks,but I can not open the link,I try to many times,can you help me?thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arangesh/Ground-Plane-Polling"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 凌晨1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arangesh/Ground-Plane-Polling] models trained on KITTI (#2)





 
You can download our inference models trained on KITTI using this link.

**Comment by arangesh** [comment]
I have created a separate [download link](http://cvrr.ucsd.edu/arangesh/gpp_kitti_inference_models.tar.gz) for you. Hopefully this should work. Note that this link will only remain active for a few days.

**Comment by zsnihao** [comment]
thank you very  much，this link can be downloaded，thanks------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月11日(星期五) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arangesh/Ground-Plane-Polling] models trained on KITTI (#2)
